const state = { projects: [], selected: null, sections: [], eventCursor: Number(localStorage.getItem("ebook-factory-event-cursor") || 0) };
const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => { const response = await fetch(path, { headers: { "content-type": "application/json", ...(options.headers || {}) }, ...options }); if (!response.ok) throw new Error((await response.text()).slice(0, 240)); return response.status === 204 ? null : response.json(); };
const showError = (id, error) => { $(id).textContent = error.message || String(error); };

function renderProjects() { const list = $("#project-list"); list.replaceChildren(); if (!state.projects.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No projects yet. Start with a small idea."; list.append(empty); return; } state.projects.forEach((project) => { const card = document.createElement("button"); card.className = "project-card"; card.innerHTML = `<h3></h3><p class="muted"></p><span class="status-pill"></span>`; card.querySelector("h3").textContent = project.title; card.querySelector("p").textContent = `${project.profile} · ${project.language}`; card.querySelector("span").textContent = project.state; card.addEventListener("click", () => selectProject(project)); list.append(card); }); }
async function loadProjects() { state.projects = await api("/projects"); renderProjects(); }
async function selectProject(project) { state.selected = project; state.eventCursor = Number(localStorage.getItem(`ebook-factory-event-cursor:${project.project_id}`) || 0); $("#studio-project-label").textContent = project.title; document.querySelector('[data-view="studio"]').click(); await Promise.all([loadMessages(), loadEvents(), loadSections(), loadReviews(), loadUsage()]); }
async function loadMessages() { if (!state.selected) return; const messages = await api(`/projects/${state.selected.project_id}/messages`); const box = $("#messages"); box.replaceChildren(); messages.forEach((message) => { const item = document.createElement("div"); item.className = `message ${message.role}`; item.textContent = message.content; box.append(item); }); }
async function loadEvents() { if (!state.selected) return; const events = await api(`/projects/${state.selected.project_id}/events?after=${state.eventCursor}`); const list = $("#events"); if (state.eventCursor === 0) list.replaceChildren(); events.forEach((event) => { const item = document.createElement("li"); item.textContent = `${event.kind} · ${new Date(event.timestamp).toLocaleTimeString()}`; list.append(item); state.eventCursor = Math.max(state.eventCursor, event.id); }); localStorage.setItem(`ebook-factory-event-cursor:${state.selected.project_id}`, String(state.eventCursor)); }
async function loadSections() {
  if (!state.selected) return;
  state.sections = await api(`/projects/${state.selected.project_id}/sections`);
  const list = $("#sections"); list.replaceChildren();
  if (!state.sections.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No accepted sections yet."; list.append(empty); return; }
  state.sections.forEach((section) => {
    const card = document.createElement("article"); card.className = "section-card";
    const heading = document.createElement("h4"); heading.textContent = `${section.order_no}. ${section.heading}`; card.append(heading);
    const editor = document.createElement("textarea"); editor.rows = 8; editor.setAttribute("aria-label", `Edit ${section.heading}`); editor.value = section.content || ""; card.append(editor);
    const actions = document.createElement("div"); actions.className = "form-actions";
    const save = document.createElement("button"); save.className = "primary"; save.textContent = "Save revision"; save.disabled = !section.latest_revision_id;
    const exportButton = document.createElement("button"); exportButton.className = "quiet"; exportButton.textContent = "Export package"; exportButton.disabled = !section.latest_revision_id;
    const result = document.createElement("p"); result.className = "muted"; result.setAttribute("aria-live", "polite");
    save.addEventListener("click", async () => { try { const revision = await api(`/sections/${section.section_id}/revisions`, { method: "POST", body: JSON.stringify({ content: editor.value, summary: "Owner revision", expected_parent_revision_id: section.latest_revision_id }) }); result.textContent = `Saved revision ${revision.revision}.`; await loadSections(); await loadEvents(); } catch (error) { result.textContent = error.message; } });
    exportButton.addEventListener("click", async () => { try { const packageResult = await api(`/projects/${state.selected.project_id}/exports/${section.latest_revision_id}`, { method: "POST", body: "{}" }); renderExports(packageResult); result.textContent = `${packageResult.package_state}; Kindle preview remains pending.`; } catch (error) { result.textContent = error.message; } });
    actions.append(save, exportButton); card.append(actions, result); list.append(card);
  });
}
function renderExports(packageResult) { const box = $("#exports"); box.replaceChildren(); const heading = document.createElement("h4"); heading.textContent = `Export: ${packageResult.title} · ${packageResult.package_state}`; box.append(heading); packageResult.artifacts.forEach((artifact) => { const link = document.createElement("a"); link.href = artifact.download_path; link.textContent = `${artifact.filename} (${artifact.byte_count} bytes)`; link.download = artifact.filename; box.append(link, document.createElement("br")); }); }
async function loadReviews() { if (!state.selected) return; const reviews = await api(`/projects/${state.selected.project_id}/reviews`); const box = $("#reviews"); box.replaceChildren(); if (!reviews.length) return; const heading = document.createElement("h4"); heading.textContent = "Review findings"; box.append(heading); reviews.forEach((finding) => { const item = document.createElement("p"); item.className = "review-finding"; item.textContent = `${finding.severity} · ${finding.criterion}: ${finding.evidence}${finding.resolution_revision_id ? " · resolved" : " · open"}`; box.append(item); }); }
async function loadUsage() { const summary = $("#usage-summary"); if (!state.selected) return; try { const usage = await api(`/usage?project_id=${state.selected.project_id}`); summary.innerHTML = `<p><strong>${usage.calls}</strong> recorded calls</p><p>Input tokens: ${usage.input_tokens ?? "unknown"} · Output tokens: ${usage.output_tokens ?? "unknown"}</p><p>Estimated cost: <strong>unknown</strong> · Reported billed cost: <strong>unknown</strong></p>`; } catch (error) { summary.textContent = error.message; } }

document.querySelectorAll(".nav-button").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll(".nav-button").forEach((other) => other.classList.toggle("active", other === button)); document.querySelectorAll(".view").forEach((view) => view.classList.toggle("active", view.id === `${button.dataset.view}-view`)); }));
$("#new-project-button").addEventListener("click", () => $("#project-form").classList.toggle("hidden"));
document.querySelectorAll("[data-cancel]").forEach((button) => button.addEventListener("click", () => $(`#${button.dataset.cancel}`).classList.add("hidden")));
$("#project-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.target); const project = await api("/projects", { method: "POST", body: JSON.stringify(Object.fromEntries(form)) }); event.target.reset(); event.target.classList.add("hidden"); await loadProjects(); await selectProject(project); } catch (error) { showError("#project-form-error", error); } });
$("#message-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.selected) return; const input = $("#message-input"); const content = input.value.trim(); if (!content) return; try { await api(`/projects/${state.selected.project_id}/messages`, { method: "POST", body: JSON.stringify({ conversation_id: state.selected.conversation_id, channel: "dashboard", content }) }); input.value = ""; await loadMessages(); await loadEvents(); } catch (error) { window.alert(error.message); } });
$("#brief-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.selected) return; const form = new FormData(event.target); try { const brief = await api(`/projects/${state.selected.project_id}/briefs`, { method: "POST", body: JSON.stringify({ structured_brief: { profile: state.selected.profile, language: state.selected.language, audience: form.get("audience"), promise_or_premise: form.get("promise"), target_length: { minimum_words: 1000, maximum_words: 3000 }, output_formats: ["markdown"], art_direction: "Simple typographic cover" } }) }); $("#brief-result").innerHTML = `<p>Revision hash: <code></code></p><button class="primary" id="approve-brief">Approve exact revision</button>`; $("#brief-result code").textContent = brief.content_hash; $("#approve-brief").addEventListener("click", async () => { const approved = await api(`/projects/${state.selected.project_id}/briefs/${brief.brief_id}/approve`, { method: "POST", body: JSON.stringify({ expected_content_hash: brief.content_hash, budget: { max_turns: 8 } }) }); $("#brief-result").insertAdjacentHTML("beforeend", `<p class="muted">Queued run: <code></code></p>`); $("#brief-result code:last-child").textContent = approved.run_id; await loadProjects(); await loadEvents(); }); } catch (error) { $("#brief-result").textContent = error.message; } });
$("#refresh-events").addEventListener("click", () => loadEvents().catch((error) => window.alert(error.message)));
$("#refresh-usage").addEventListener("click", () => loadUsage().catch((error) => window.alert(error.message)));
$("#provider-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); const values = Object.fromEntries(form); try { await api(`/providers/${encodeURIComponent(values.provider)}`, { method: "PUT", body: JSON.stringify(values) }); $("#provider-result").textContent = "Metadata saved; credential bytes remain outside PostgreSQL."; await loadProviders(); } catch (error) { $("#provider-result").textContent = error.message; } });
async function loadProviders() { const providers = await api("/providers"); const list = $("#provider-list"); list.replaceChildren(); if (!providers.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No provider metadata saved."; list.append(empty); return; } providers.forEach((provider) => { const item = document.createElement("p"); const name = document.createElement("strong"); name.textContent = provider.provider; item.append(name, ` · ${provider.credential_configured ? "credential reference set" : "credential not configured"}`); list.append(item); }); }
await loadProjects(); await loadProviders(); setInterval(() => state.selected && loadEvents().catch(() => {}), 3000);
