const state = { projects: [], selected: null, sections: [], providers: [], catalog: null, eventCursor: 0, streamController: null, liveAssistant: null };
const $ = (selector) => document.querySelector(selector);
const ownerToken = () => sessionStorage.getItem("ebook-factory-owner-token") || "";
const api = async (path, options = {}) => { const headers = { "content-type": "application/json", ...(options.headers || {}) }; const token = ownerToken(); if (token) headers.Authorization = `Bearer ${token}`; const response = await fetch(path, { headers, ...options }); if (!response.ok) { const error = new Error((await response.text()).slice(0, 240)); error.status = response.status; throw error; } return response.status === 204 ? null : response.json(); };
const showError = (id, error) => { $(id).textContent = error.message || String(error); };
function addSavedOption(select, value, label) { if (!value) return; const option = [...select.options].find((candidate) => candidate.value === value); if (option) { option.selected = true; return; } const saved = document.createElement("option"); saved.value = value; saved.textContent = label + " (saved; unavailable)"; saved.selected = true; select.append(saved); }
function populateCatalogSelects(saved = {}) { const models = state.catalog?.models || []; const providerSelect = $("#provider-select"); const modelSelects = [$("#orchestration-model"), $("#drafting-model"), $("#review-model")]; providerSelect.replaceChildren(); [...new Set(models.map((model) => model.provider))].sort().forEach((provider) => { const option = document.createElement("option"); option.value = provider; option.textContent = provider; providerSelect.append(option); }); addSavedOption(providerSelect, saved.provider, "Provider"); modelSelects.forEach((select) => { select.replaceChildren(); models.forEach((model) => { const option = document.createElement("option"); option.value = model.qualified_model; option.textContent = model.qualified_model + " · context " + model.context + " · max " + model.max_output; select.append(option); }); }); addSavedOption($("#orchestration-model"), saved.orchestration_model, "Main orchestrator model"); addSavedOption($("#drafting-model"), saved.drafting_model, "Drafting model"); addSavedOption($("#review-model"), saved.review_model, "Review model"); }
function currentCatalogSelections() { return { provider: $("#provider-select").value, orchestration_model: $("#orchestration-model").value, drafting_model: $("#drafting-model").value, review_model: $("#review-model").value }; }
function filterCatalogModels(provider) { const models = (state.catalog?.models || []).filter((model) => model.provider === provider); const labels = ["Main orchestrator model", "Drafting model", "Review model"]; [$("#orchestration-model"), $("#drafting-model"), $("#review-model")].forEach((select, index) => { const selected = select.value; const known = state.catalog?.models.find((model) => model.qualified_model === selected); const staleQualified = !known && selected.includes("/") && selected.split("/", 1)[0] !== provider; select.replaceChildren(); models.forEach((model) => { const option = document.createElement("option"); option.value = model.qualified_model; option.textContent = model.qualified_model + " · context " + model.context + " · max " + model.max_output; select.append(option); }); if (!staleQualified && (!known || known.provider === provider)) addSavedOption(select, selected, labels[index]); if (!select.value && select.options.length) select.selectedIndex = 0; }); }
function bindCatalogCoherence() { $("#provider-select").addEventListener("change", () => filterCatalogModels($("#provider-select").value)); [$("#orchestration-model"), $("#drafting-model"), $("#review-model")].forEach((select) => select.addEventListener("change", () => { const selected = state.catalog?.models.find((model) => model.qualified_model === select.value); if (selected) { $("#provider-select").value = selected.provider; filterCatalogModels(selected.provider); select.value = selected.qualified_model; } })); }
async function loadCatalog() { const status = $("#catalog-status"); const selections = currentCatalogSelections(); try { state.catalog = await api("/providers/catalog"); status.textContent = state.catalog.models.length + " installed Pi models · source: " + state.catalog.source + " · fetched " + new Date(state.catalog.fetched_at).toLocaleString(); populateCatalogSelects(selections); if (selections.provider) filterCatalogModels(selections.provider); } catch (error) { state.catalog = null; status.textContent = "Pi model catalog unavailable: " + error.message; populateCatalogSelects(selections); } }

function renderProjects() { const list = $("#project-list"); list.replaceChildren(); if (!state.projects.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No projects yet. Start with a small idea."; list.append(empty); return; } state.projects.forEach((project) => { const card = document.createElement("button"); card.className = "project-card"; card.innerHTML = `<h3></h3><p class="muted"></p><span class="status-pill"></span>`; card.querySelector("h3").textContent = project.title; card.querySelector("p").textContent = `${project.profile} · ${project.language}`; card.querySelector("span").textContent = project.state; card.addEventListener("click", () => selectProject(project)); list.append(card); }); }
async function loadProjects() { state.projects = await api("/projects"); renderProjects(); }
async function selectProject(project) { state.streamController?.abort(); state.selected = project; state.liveAssistant = null; state.eventCursor = Number(localStorage.getItem(`ebook-factory-event-cursor:${project.project_id}`) || 0); $("#studio-project-label").textContent = project.title; document.querySelector('[data-view="studio"]').click(); await Promise.all([loadMessages(), loadEvents(), loadSections(), loadReviews(), loadArtifacts(), loadUsage()]); startEventStream(); }
async function loadMessages() { if (!state.selected) return; const messages = await api(`/projects/${state.selected.project_id}/messages`); const box = $("#messages"); box.replaceChildren(); messages.forEach((message) => { const item = document.createElement("div"); item.className = `message ${message.role}`; item.textContent = message.content; box.append(item); }); }
function applyEvent(event) { if (!state.selected || event.project_id !== state.selected.project_id || event.id <= state.eventCursor) return; const list = $("#events"); const item = document.createElement("li"); item.textContent = `${event.kind} · ${new Date(event.timestamp).toLocaleTimeString()}`; list.append(item); state.eventCursor = event.id; localStorage.setItem(`ebook-factory-event-cursor:${state.selected.project_id}`, String(state.eventCursor)); const payload = event.payload || {}; if (event.kind === "orchestrator.turn.delta" && payload.delta) { if (!state.liveAssistant || state.liveAssistant.turnId !== payload.turn_id) { const element = document.createElement("div"); element.className = "message assistant streaming"; element.setAttribute("aria-live", "polite"); $("#messages").append(element); state.liveAssistant = { turnId: payload.turn_id, text: "", element }; } state.liveAssistant.text += payload.delta; state.liveAssistant.element.textContent = state.liveAssistant.text; } if (["orchestrator.turn.completed", "orchestrator.turn.failed"].includes(event.kind)) { state.liveAssistant = null; loadMessages().catch(() => {}); } }
async function loadEvents() { if (!state.selected) return; const events = await api(`/projects/${state.selected.project_id}/events?after=${state.eventCursor}`); if (state.eventCursor === 0) $("#events").replaceChildren(); events.forEach(applyEvent); }
function parseSseBlock(block) { const data = block.split("\n").filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trim()).join("\n"); return data ? JSON.parse(data) : null; }
async function startEventStream() { const projectId = state.selected?.project_id; if (!projectId) return; const controller = new AbortController(); state.streamController = controller; while (!controller.signal.aborted && state.selected?.project_id === projectId) { try { const response = await fetch(`/projects/${projectId}/events/stream?after=${state.eventCursor}&follow=true`, { headers: { Authorization: `Bearer ${ownerToken()}` }, signal: controller.signal }); if (!response.ok) throw new Error(`event stream ${response.status}`); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (!controller.signal.aborted) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const blocks = buffer.split("\n\n"); buffer = blocks.pop() || ""; blocks.forEach((block) => { try { const event = parseSseBlock(block); if (event) applyEvent(event); } catch { /* reconnect from the durable cursor */ } }); } } catch (error) { if (controller.signal.aborted) break; await new Promise((resolve) => setTimeout(resolve, 1000)); } } }
async function loadSections() {
  if (!state.selected) return;
  state.sections = await api(`/projects/${state.selected.project_id}/sections`);
  const list = $("#sections"); list.replaceChildren();
  if (!state.sections.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No accepted sections yet."; list.append(empty); return; }
  state.sections.forEach((section) => {
    const card = document.createElement("article"); card.className = "section-card";
    const heading = document.createElement("h4"); heading.textContent = `${section.order_no}. ${section.heading}`; card.append(heading);
    const editor = document.createElement("textarea"); editor.rows = 8; editor.setAttribute("aria-label", `Edit ${section.heading}`); editor.value = section.content || ""; card.append(editor);
    const actions = document.createElement("div"); actions.className = "form-actions";
    const save = document.createElement("button"); save.className = "primary"; save.textContent = "Save revision"; save.disabled = !section.latest_revision_id;
    const exportButton = document.createElement("button"); exportButton.className = "quiet"; exportButton.textContent = "Export package"; exportButton.disabled = !section.latest_revision_id;
    const result = document.createElement("p"); result.className = "muted"; result.setAttribute("aria-live", "polite");
    save.addEventListener("click", async () => { try { const revision = await api(`/sections/${section.section_id}/revisions`, { method: "POST", body: JSON.stringify({ content: editor.value, summary: "Owner revision", expected_parent_revision_id: section.latest_revision_id }) }); result.textContent = `Saved revision ${revision.revision}.`; await loadSections(); await loadEvents(); } catch (error) { result.textContent = error.message; } });
    exportButton.addEventListener("click", async () => { try { const packageResult = await api(`/projects/${state.selected.project_id}/exports/${section.latest_revision_id}`, { method: "POST", body: "{}" }); renderExports(packageResult); result.textContent = `${packageResult.package_state}; Kindle preview remains pending.`; } catch (error) { result.textContent = error.message; } });
    actions.append(save, exportButton); card.append(actions, result); list.append(card);
  });
}
function renderExports(packageResult) { const box = $("#exports"); box.replaceChildren(); const heading = document.createElement("h4"); heading.textContent = `Export: ${packageResult.title} · ${packageResult.package_state}`; box.append(heading); packageResult.artifacts.forEach((artifact) => { const link = document.createElement("a"); link.href = artifact.download_path; link.textContent = `${artifact.filename} (${artifact.byte_count} bytes)`; link.download = artifact.filename; box.append(link, document.createElement("br")); }); }
function reviewStateLabel(state) { return ({ approved: "Approved", revision_requested: "Revision requested", pending: "Review pending" })[state] || "Review pending"; }
function appendArtifactReview(item, artifact) {
  const review = document.createElement("div"); review.className = "artifact-review";
  const heading = document.createElement("strong"); heading.textContent = `Owner review: ${reviewStateLabel(artifact.owner_review_state)}`; review.append(heading);
  if (artifact.owner_review_note) { const note = document.createElement("p"); note.className = "muted artifact-review-note"; note.textContent = artifact.owner_review_note; review.append(note); }
  if (artifact.owner_reviewed_at) { const reviewed = document.createElement("p"); reviewed.className = "muted artifact-review-date"; reviewed.textContent = `Reviewed ${new Date(artifact.owner_reviewed_at).toLocaleString()}`; review.append(reviewed); }
  const noteLabel = document.createElement("label"); noteLabel.textContent = "Note (optional)";
  const noteInput = document.createElement("textarea"); noteInput.rows = 2; noteInput.placeholder = "Add context for this decision"; noteInput.className = "artifact-review-note-input"; noteLabel.append(noteInput);
  const actions = document.createElement("div"); actions.className = "form-actions artifact-review-actions";
  const result = document.createElement("p"); result.className = "muted artifact-review-result"; result.setAttribute("aria-live", "polite"); result.setAttribute("role", "status");
  [["approve", "Approve", "primary"], ["request_revision", "Request revision", "quiet"]].forEach(([decision, label, className]) => {
    const button = document.createElement("button"); button.type = "button"; button.className = className; button.textContent = label;
    button.addEventListener("click", async () => {
      actions.querySelectorAll("button").forEach((control) => { control.disabled = true; }); result.textContent = `${label}…`;
      try { await api(`/projects/${state.selected.project_id}/artifacts/${artifact.artifact_id}/review`, { method: "POST", body: JSON.stringify({ decision, note: noteInput.value.trim() || null, expected_owner_review_state: artifact.owner_review_state }) }); result.textContent = `${label} saved.`; await loadArtifacts(); }
      catch (error) { result.textContent = error.status === 409 ? "Review conflict: this artifact changed elsewhere. Reloading its current state…" : `Could not save review: ${error.message}`; actions.querySelectorAll("button").forEach((control) => { control.disabled = false; }); if (error.status === 409) await loadArtifacts(); }
    }); actions.append(button);
  });
  review.append(noteLabel, actions, result); item.append(review);
}
async function loadArtifacts() { if (!state.selected) return; const box = $("#artifacts"); try { const artifacts = await api(`/projects/${state.selected.project_id}/artifacts`); box.replaceChildren(); if (!artifacts.length) { box.textContent = "No production artifacts loaded."; return; } artifacts.forEach((artifact) => { const item = document.createElement("article"); item.className = "usage-call"; const link = document.createElement("a"); link.href = artifact.download_path; link.download = artifact.relative_path.split("/").pop(); link.textContent = `${artifact.relative_path} · ${artifact.byte_count.toLocaleString()} bytes`; const meta = document.createElement("p"); meta.className = "muted"; meta.textContent = `${artifact.mime_type} · ${artifact.validation_state} · SHA-256 ${artifact.sha256}`; item.append(link, meta); const isReviewableImage = artifact.mime_type.startsWith("image/") && !artifact.relative_path.startsWith("exports/"); if (artifact.mime_type.startsWith("image/")) { const image = document.createElement("img"); image.src = artifact.download_path; image.alt = artifact.relative_path; image.loading = "lazy"; image.className = "artifact-preview"; item.append(image); } if (isReviewableImage) appendArtifactReview(item, artifact); box.append(item); }); } catch (error) { box.textContent = `Artifacts unavailable: ${error.message}`; } }
async function loadReviews() { if (!state.selected) return; const reviews = await api(`/projects/${state.selected.project_id}/reviews`); const box = $("#reviews"); box.replaceChildren(); if (!reviews.length) return; const heading = document.createElement("h4"); heading.textContent = "Review findings"; box.append(heading); reviews.forEach((finding) => { const item = document.createElement("p"); item.className = "review-finding"; item.textContent = `${finding.severity} · ${finding.criterion}: ${finding.evidence}${finding.resolution_revision_id ? " · resolved" : " · open"}`; box.append(item); }); }
function quotaWindowLabel(snapshot, accountCount) { const seconds = Number(snapshot.window_seconds); const name = seconds === 18000 ? "5-hour window" : seconds === 604800 ? "7-day window" : "Provider window"; return accountCount > 1 ? `${name} · account ${snapshot.account_index}` : name; }
async function loadQuota() { const summary = $("#quota-summary"); summary.textContent = "Refreshing live Codex limits…"; try { const live = await api("/quota/live"); summary.replaceChildren(); if (!live.windows?.length) { summary.textContent = "Codex limits unavailable: no measurable live windows were returned."; return; } const accountCount = Math.max(...live.windows.map((window) => Number(window.account_index) || 1)); const source = document.createElement("p"); source.className = "muted"; source.textContent = `Live source: ${live.source} · fetched ${new Date(live.fetched_at).toLocaleString()}`; summary.append(source); live.windows.forEach((window) => { const item = document.createElement("article"); item.className = "usage-call"; const heading = document.createElement("strong"); heading.textContent = quotaWindowLabel(window, accountCount); const details = document.createElement("p"); details.className = "muted"; details.textContent = `${window.used}% used · ${window.remaining}% remaining · resets ${window.reset}`; item.append(heading, details); summary.append(item); }); } catch (error) { summary.textContent = "Codex live limits unavailable: " + error.message; } }
function displayModel(call) { const prefix = `${call.provider}/`; return call.model.startsWith(prefix) ? call.model.slice(prefix.length) : call.model; }
function displayPurpose(purpose) { return purpose.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function displayTokens(value) { return value == null ? "not reported" : Number(value).toLocaleString(); }
function renderUsageCalls(calls) {
  const summary = $("#usage-calls");
  summary.replaceChildren();
  if (!calls.length) { summary.textContent = "No provider calls recorded for this scope."; return; }
  calls.forEach((call) => {
    const item = document.createElement("article"); item.className = "usage-call";
    const heading = document.createElement("strong"); heading.textContent = `${displayPurpose(call.purpose)} · ${displayModel(call)}`;
    const meta = document.createElement("p"); meta.className = "muted"; meta.textContent = `${call.outcome} · ${displayTokens(call.input_tokens)} input · ${displayTokens(call.output_tokens)} output · subscription billing not reported`;
    const lineage = document.createElement("details"); const summaryLine = document.createElement("summary"); summaryLine.textContent = "Show lineage"; const id = document.createElement("code"); id.textContent = `${call.provider} · ${call.call_id}`; lineage.append(summaryLine, id);
    item.append(heading, meta, lineage); summary.append(item);
  });
}
async function loadUsage() {
  const summary = $("#usage-summary");
  try {
    const scope = state.selected ? `?project_id=${state.selected.project_id}` : "";
    const usage = await api(`/usage${scope}`); summary.innerHTML = `<p><strong>${usage.calls}</strong> ${state.selected ? "project" : "workspace"} calls recorded</p><p>Input tokens: ${displayTokens(usage.input_tokens)} · Output tokens: ${displayTokens(usage.output_tokens)} · Reasoning tokens: ${displayTokens(usage.reasoning_tokens)}</p><p class="muted">Subscription billing is not reported by the provider.</p>`;
    try { renderUsageCalls(await api(`/usage/calls${scope}`)); } catch { renderUsageCalls([]); }
    await loadQuota();
  } catch (error) { summary.textContent = error.message; }
}

document.querySelectorAll(".nav-button").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll(".nav-button").forEach((other) => other.classList.toggle("active", other === button)); document.querySelectorAll(".view").forEach((view) => view.classList.toggle("active", view.id === `${button.dataset.view}-view`)); if (button.dataset.view === "usage") loadUsage().catch((error) => { $("#usage-summary").textContent = error.message; }); }));
$("#new-project-button").addEventListener("click", () => $("#project-form").classList.toggle("hidden"));
document.querySelectorAll("[data-cancel]").forEach((button) => button.addEventListener("click", () => $(`#${button.dataset.cancel}`).classList.add("hidden")));
$("#project-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.target); const project = await api("/projects", { method: "POST", body: JSON.stringify(Object.fromEntries(form)) }); event.target.reset(); event.target.classList.add("hidden"); await loadProjects(); await selectProject(project); } catch (error) { showError("#project-form-error", error); } });
$("#message-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.selected) return; const input = $("#message-input"); const content = input.value.trim(); if (!content) return; const external_dedupe_id = crypto.randomUUID(); try { await api(`/projects/${state.selected.project_id}/messages`, { method: "POST", body: JSON.stringify({ conversation_id: state.selected.conversation_id, channel: "dashboard", external_dedupe_id, content }) }); input.value = ""; await loadMessages(); await loadEvents(); } catch (error) { window.alert(error.message); } });
$("#brief-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.selected) return; const form = new FormData(event.target); const pages = form.get("length_mode") === "pages"; const minimum = Number(form.get(pages ? "minimum_pages" : "minimum_words")); const maximum = Number(form.get(pages ? "maximum_pages" : "maximum_words")); if (!Number.isInteger(minimum) || !Number.isInteger(maximum) || minimum > maximum) { $("#brief-result").textContent = "The minimum must not exceed the maximum."; return; } const target = pages ? { target_pages: { minimum, maximum } } : { target_length: { minimum_words: minimum, maximum_words: maximum } }; try { const brief = await api(`/projects/${state.selected.project_id}/briefs`, { method: "POST", body: JSON.stringify({ structured_brief: { profile: state.selected.profile, language: state.selected.language, audience: form.get("audience"), promise_or_premise: form.get("promise"), ...target, output_formats: ["markdown"], art_direction: "Simple typographic cover" } }) }); $("#brief-result").innerHTML = `<p>Revision hash: <code></code></p><button class="primary" id="approve-brief">Approve exact revision</button>`; $("#brief-result code").textContent = brief.content_hash; $("#approve-brief").addEventListener("click", async () => { const maxTurns = pages ? 24 : 8; const approved = await api(`/projects/${state.selected.project_id}/briefs/${brief.brief_id}/approve`, { method: "POST", body: JSON.stringify({ expected_content_hash: brief.content_hash, budget: { max_turns: maxTurns } }) }); $("#brief-result").insertAdjacentHTML("beforeend", `<p class="muted">Queued run: <code></code></p>`); $("#brief-result code:last-child").textContent = approved.run_id; await loadProjects(); await loadEvents(); }); } catch (error) { $("#brief-result").textContent = error.message; } });
$("#refresh-catalog").addEventListener("click", () => loadCatalog().then(() => loadProviders()).catch((error) => { $("#catalog-status").textContent = error.message; }));
$("#refresh-events").addEventListener("click", () => loadEvents().catch((error) => window.alert(error.message)));
$("#refresh-usage").addEventListener("click", () => loadUsage().catch((error) => window.alert(error.message)));
$("#provider-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); const values = Object.fromEntries(form); const mismatched = [values.orchestration_model, values.drafting_model, values.review_model].some((model) => model && state.catalog?.models.some((entry) => entry.qualified_model === model && entry.provider !== values.provider)); if (mismatched) { $("#provider-result").textContent = "Choose models belonging to the selected provider."; return; } try { await api(`/providers/${encodeURIComponent(values.provider)}`, { method: "PUT", body: JSON.stringify(values) }); $("#provider-result").textContent = "Metadata saved; credential bytes remain outside PostgreSQL."; await loadProviders(); } catch (error) { $("#provider-result").textContent = error.message; } });
async function loadProviders() { const providers = await api("/providers"); const list = $("#provider-list"); list.replaceChildren(); if (!providers.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No provider metadata saved."; list.append(empty); return; } providers.forEach((provider) => { const item = document.createElement("div"); const line = document.createElement("p"); const name = document.createElement("strong"); name.textContent = provider.provider; line.append(name, ` · ${provider.protocol || "protocol not set"} · ${provider.credential_configured ? "credential reference set" : "credential not configured"}`); const button = document.createElement("button"); button.className = "quiet"; button.type = "button"; button.textContent = "Test connection"; button.addEventListener("click", () => testProviderConnection(provider.provider, button)); item.append(line, button); list.append(item); }); }
async function testProviderConnection(provider, button) { const status = $("#provider-result"); button.disabled = true; status.textContent = `Testing ${provider}…`; try { const result = await api(`/providers/${encodeURIComponent(provider)}/connection-test`, { method: "POST", body: "{}" }); const details = result.http_status ? ` · HTTP ${result.http_status}` : ""; status.textContent = `${provider}: ${result.outcome}${details}${result.response_id ? ` · response ${result.response_id}` : ""}`; } catch (error) { status.textContent = `${provider}: ${error.message}`; } finally { button.disabled = false; } }
async function loadTelegramStatus() { const status = $("#telegram-status"); try { const telegram = await api("/telegram/status"); status.textContent = telegram.configured ? `Configured · ${telegram.linked_chat_count} owner chat(s) · ${telegram.linked_project_count} project link(s) · next update ${telegram.next_update_id}` : "Not configured. Set the local bot token and allowlisted chat/sender IDs; no credentials are shown here."; } catch (error) { status.textContent = error.message; } }
$("#refresh-telegram").addEventListener("click", () => loadTelegramStatus());
$("#telegram-link-form").addEventListener("submit", async (event) => { event.preventDefault(); const result = $("#telegram-link-result"); const button = $("#telegram-link-button"); const input = $("#telegram-chat-id"); result.textContent = ""; input.setAttribute("aria-invalid", "false"); if (!state.selected) { result.textContent = "Select a project in Studio first, then try linking again."; return; } const project = state.selected; const chatId = Number(new FormData(event.target).get("chat_id")); if (!Number.isSafeInteger(chatId)) { input.setAttribute("aria-invalid", "true"); result.textContent = "Enter a valid numeric Telegram chat ID."; return; } button.disabled = true; result.textContent = `Setting ${project.title} active for chat ${chatId}…`; try { const telegram = await api(`/projects/${project.project_id}/telegram/link`, { method: "POST", body: JSON.stringify({ chat_id: chatId }) }); result.textContent = `Chat ${chatId} now uses ${project.title}; all projects remain linked. ${telegram.linked_project_count} project link(s) active.`; await loadTelegramStatus(); } catch (error) { let detail = error.message || "request failed"; try { const parsed = JSON.parse(detail); detail = parsed.detail || detail; } catch { /* API may return plain text */ } result.textContent = `Could not set chat ${chatId}: ${detail}`; } finally { button.disabled = false; } });
$("#brief-form [name=length_mode]").addEventListener("change", (event) => { $("#page-target-fields").classList.toggle("hidden", event.target.value !== "pages"); $("#word-target-fields").classList.toggle("hidden", event.target.value !== "words"); });
async function boot() { $("#auth-view").classList.add("hidden"); $("#app-shell").classList.remove("hidden"); bindCatalogCoherence(); await loadProjects(); await loadCatalog(); await loadProviders(); const savedProviders = await api("/providers"); const saved = savedProviders.find((provider) => provider.provider === $("#provider-select").value) || savedProviders[0] || {}; populateCatalogSelects(saved); savedProviders.slice(1).forEach((provider) => addSavedOption($("#provider-select"), provider.provider, "Provider")); if (saved.provider) filterCatalogModels(saved.provider); await loadTelegramStatus(); }
$("#auth-form").addEventListener("submit", async (event) => { event.preventDefault(); const error = $("#auth-error"); error.textContent = ""; const token = $("#owner-token").value; try { await fetch("/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token }) }).then(async (response) => { if (!response.ok) throw new Error((await response.text()).slice(0, 240)); }); sessionStorage.setItem("ebook-factory-owner-token", token); $("#owner-token").value = ""; await boot(); } catch (reason) { error.textContent = reason.message || "Sign in failed"; } });
if (ownerToken()) { api("/auth/verify").then(boot).catch(() => sessionStorage.removeItem("ebook-factory-owner-token")); }
