const state = { projects: [], selected: null, eventCursor: Number(localStorage.getItem("ebook-factory-event-cursor") || 0) };
const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => { const response = await fetch(path, { headers: { "content-type": "application/json", ...(options.headers || {}) }, ...options }); if (!response.ok) throw new Error((await response.text()).slice(0, 240)); return response.status === 204 ? null : response.json(); };
const showError = (id, error) => { $(id).textContent = error.message || String(error); };

function renderProjects() { const list = $("#project-list"); list.replaceChildren(); if (!state.projects.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No projects yet. Start with a small idea."; list.append(empty); return; } state.projects.forEach((project) => { const card = document.createElement("button"); card.className = "project-card"; card.innerHTML = `<h3></h3><p class="muted"></p><span class="status-pill"></span>`; card.querySelector("h3").textContent = project.title; card.querySelector("p").textContent = `${project.profile} · ${project.language}`; card.querySelector("span").textContent = project.state; card.addEventListener("click", () => selectProject(project)); list.append(card); }); }
async function loadProjects() { state.projects = await api("/projects"); renderProjects(); }
async function selectProject(project) { state.selected = project; state.eventCursor = Number(localStorage.getItem(`ebook-factory-event-cursor:${project.project_id}`) || 0); $("#studio-project-label").textContent = project.title; document.querySelector('[data-view="studio"]').click(); await loadMessages(); await loadEvents(); }
async function loadMessages() { if (!state.selected) return; const messages = await api(`/projects/${state.selected.project_id}/messages`); const box = $("#messages"); box.replaceChildren(); messages.forEach((message) => { const item = document.createElement("div"); item.className = `message ${message.role}`; item.textContent = message.content; box.append(item); }); }
async function loadEvents() { if (!state.selected) return; const events = await api(`/projects/${state.selected.project_id}/events?after=${state.eventCursor}`); const list = $("#events"); if (state.eventCursor === 0) list.replaceChildren(); events.forEach((event) => { const item = document.createElement("li"); item.textContent = `${event.kind} · ${new Date(event.timestamp).toLocaleTimeString()}`; list.append(item); state.eventCursor = Math.max(state.eventCursor, event.id); }); localStorage.setItem(`ebook-factory-event-cursor:${state.selected.project_id}`, String(state.eventCursor)); }

document.querySelectorAll(".nav-button").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll(".nav-button").forEach((other) => other.classList.toggle("active", other === button)); document.querySelectorAll(".view").forEach((view) => view.classList.toggle("active", view.id === `${button.dataset.view}-view`)); }));
$("#new-project-button").addEventListener("click", () => $("#project-form").classList.toggle("hidden"));
document.querySelectorAll("[data-cancel]").forEach((button) => button.addEventListener("click", () => $(`#${button.dataset.cancel}`).classList.add("hidden")));
$("#project-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.target); const project = await api("/projects", { method: "POST", body: JSON.stringify(Object.fromEntries(form)) }); event.target.reset(); event.target.classList.add("hidden"); await loadProjects(); await selectProject(project); } catch (error) { showError("#project-form-error", error); } });
$("#message-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.selected) return; const input = $("#message-input"); const content = input.value.trim(); if (!content) return; try { await api(`/projects/${state.selected.project_id}/messages`, { method: "POST", body: JSON.stringify({ conversation_id: state.selected.conversation_id, channel: "dashboard", content }) }); input.value = ""; await loadMessages(); await loadEvents(); } catch (error) { window.alert(error.message); } });
$("#brief-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.selected) return; const form = new FormData(event.target); try { const brief = await api(`/projects/${state.selected.project_id}/briefs`, { method: "POST", body: JSON.stringify({ structured_brief: { profile: state.selected.profile, language: state.selected.language, audience: form.get("audience"), promise_or_premise: form.get("promise"), target_length: { minimum_words: 1000, maximum_words: 3000 }, output_formats: ["markdown"], art_direction: "Simple typographic cover" } }) }); $("#brief-result").innerHTML = `<p>Revision hash: <code></code></p><button class="primary" id="approve-brief">Approve exact revision</button>`; $("#brief-result code").textContent = brief.content_hash; $("#approve-brief").addEventListener("click", async () => { const approved = await api(`/projects/${state.selected.project_id}/briefs/${brief.brief_id}/approve`, { method: "POST", body: JSON.stringify({ expected_content_hash: brief.content_hash, budget: { max_turns: 8 } }) }); $("#brief-result").insertAdjacentHTML("beforeend", `<p class="muted">Queued run: <code></code></p>`); $("#brief-result code:last-child").textContent = approved.run_id; await loadProjects(); await loadEvents(); }); } catch (error) { $("#brief-result").textContent = error.message; } });
$("#refresh-events").addEventListener("click", () => loadEvents().catch((error) => window.alert(error.message)));
$("#provider-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); const values = Object.fromEntries(form); try { await api(`/providers/${encodeURIComponent(values.provider)}`, { method: "PUT", body: JSON.stringify(values) }); $("#provider-result").textContent = "Metadata saved; credential bytes remain outside PostgreSQL."; await loadProviders(); } catch (error) { $("#provider-result").textContent = error.message; } });
async function loadProviders() { const providers = await api("/providers"); const list = $("#provider-list"); list.replaceChildren(); if (!providers.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No provider metadata saved."; list.append(empty); return; } providers.forEach((provider) => { const item = document.createElement("p"); const name = document.createElement("strong"); name.textContent = provider.provider; item.append(name, ` · ${provider.credential_configured ? "credential reference set" : "credential not configured"}`); list.append(item); }); }
await loadProjects(); await loadProviders(); setInterval(() => state.selected && loadEvents().catch(() => {}), 3000);
