"""add project relationship foreign keys.

Revision ID: 250e73df76d6
Revises: 74fba9d42191
Create Date: 2026-09-18 22:50:26.974899
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '250e73df76d6'
down_revision: Union[str, Sequence[str], None] = '74fba9d42191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('projects', recreate='always') as batch_op:
            batch_op.create_foreign_key('fk_projects_conversation', 'conversations', ['conversation_id'], ['id'])
            batch_op.create_foreign_key('fk_projects_active_brief', 'brief_revisions', ['active_brief_id'], ['id'])
    else:
        op.create_foreign_key('fk_projects_conversation', 'projects', 'conversations', ['conversation_id'], ['id'])
        op.create_foreign_key('fk_projects_active_brief', 'projects', 'brief_revisions', ['active_brief_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('projects', recreate='always') as batch_op:
            batch_op.drop_constraint('fk_projects_active_brief', type_='foreignkey')
            batch_op.drop_constraint('fk_projects_conversation', type_='foreignkey')
    else:
        op.drop_constraint('fk_projects_active_brief', 'projects', type_='foreignkey')
        op.drop_constraint('fk_projects_conversation', 'projects', type_='foreignkey')
    # ### end Alembic commands ###
